#!/usr/bin/env python3
"""Optimize MathTutor's conversational instruction block with DSPy GEPA."""

import json
import os
from pathlib import Path

import dspy
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[2]
DATA = Path(__file__).with_name("scenarios.json")
OUTPUT = ROOT / "supabase/functions/tutor/optimized_instructions.ts"


class TutorReply(dspy.Signature):
    """Give one concise, guided math-tutoring response without revealing the final answer."""

    student_context: str = dspy.InputField()
    visible_work: str = dspy.InputField()
    student_question: str = dspy.InputField()
    reply: str = dspy.OutputField()


class ReplyJudge(dspy.Signature):
    """Score a tutor reply using the scenario's expert guidance."""

    scenario: str = dspy.InputField()
    reference_guidance: str = dspy.InputField()
    reply: str = dspy.InputField()
    correctness: float = dspy.OutputField(desc="0 to 1")
    pedagogy: float = dspy.OutputField(desc="0 to 1")
    specificity: float = dspy.OutputField(desc="0 to 1")
    restraint: float = dspy.OutputField(desc="0 to 1; 1 means no final-answer leakage")
    feedback: str = dspy.OutputField(desc="Concrete reason and one improvement")


def metric_for(judge_lm):
    judge = dspy.Predict(ReplyJudge)

    def metric(example, prediction, trace=None, pred_name=None, pred_trace=None):
        with dspy.context(lm=judge_lm):
            result = judge(
                scenario=(
                    f"Context: {example.student_context}\n"
                    f"Visible work: {example.visible_work}\n"
                    f"Question: {example.student_question}"
                ),
                reference_guidance=example.reference_guidance,
                reply=prediction.reply,
            )
        values = [
            float(result.correctness),
            float(result.pedagogy),
            float(result.specificity),
            float(result.restraint),
        ]
        score = sum(max(0.0, min(1.0, value)) for value in values) / len(values)
        return dspy.Prediction(score=score, feedback=result.feedback)

    return metric


def main():
    load_dotenv(ROOT / ".env")
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit("OPENAI_API_KEY is missing from the repository .env")

    student_model = os.environ.get("TUTOR_MODEL", "openai/gpt-5.4-mini")
    reflection_model = os.environ.get("REFLECTION_MODEL", "openai/gpt-5.5")
    dspy.configure(lm=dspy.LM(student_model, api_key=api_key))
    judge_lm = dspy.LM(reflection_model, api_key=api_key)

    rows = json.loads(DATA.read_text())
    examples = [
        dspy.Example(**row).with_inputs(
            "student_context", "visible_work", "student_question"
        )
        for row in rows
    ]
    split = max(1, int(len(examples) * 0.75))
    optimizer = dspy.GEPA(
        metric=metric_for(judge_lm),
        reflection_lm=judge_lm,
        max_metric_calls=int(os.environ.get("GEPA_MAX_METRIC_CALLS", "40")),
        num_threads=2,
    )
    optimized = optimizer.compile(
        dspy.ChainOfThought(TutorReply),
        trainset=examples[:split],
        valset=examples[split:],
    )
    instructions = optimized.predict.signature.instructions.strip()
    escaped = instructions.replace("`", "\\`").replace("${", "\\${")
    OUTPUT.write_text(
        "// Generated by tools/gepa/optimize.py. Review before deploying.\n"
        "export const OPTIMIZED_TUTOR_INSTRUCTIONS = `\n"
        f"{escaped}\n"
        "`.trim();\n"
    )
    print(f"Wrote optimized instructions to {OUTPUT}")


if __name__ == "__main__":
    main()
